#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------
# publish-sync.sh
#
# Manage publishing and upstream syncing for @njdamstra scoped fork
# of ZachHandley/AppwriteUtils.
#
# A flag is REQUIRED. Run without flags to see usage.
# ------------------------------------------------------------------

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# ---- Parse flags ----
DO_SYNC=false
DO_PUBLISH=false

for arg in "$@"; do
  case "$arg" in
    --sync)         DO_SYNC=true ;;
    --publish)      DO_PUBLISH=true ;;
    --sync-publish) DO_SYNC=true; DO_PUBLISH=true ;;
    --help|-h)      ;; # fall through to usage
    *)
      echo "Unknown flag: $arg"
      echo ""
      ;; # fall through to usage
  esac
done

if [ "$DO_SYNC" = false ] && [ "$DO_PUBLISH" = false ]; then
  echo "publish-sync.sh — Publish and/or sync upstream for @njdamstra/appwrite-utils"
  echo ""
  echo "USAGE:"
  echo "  ./scripts/publish-sync.sh <flag>"
  echo ""
  echo "FLAGS (at least one required):"
  echo "  --sync           Fetch & merge latest from ZachHandley/AppwriteUtils,"
  echo "                   re-apply @njdamstra scope renames, install, and build."
  echo ""
  echo "  --publish        Build and publish all packages to npm."
  echo "                   Use this after making your own changes."
  echo ""
  echo "  --sync-publish   Do both: sync upstream first, then publish."
  echo "                   Use this to pull Zach's latest and ship it."
  echo ""
  echo "EXAMPLES:"
  echo "  # Pull Zach's latest changes (no publish)"
  echo "  ./scripts/publish-sync.sh --sync"
  echo ""
  echo "  # Publish your own changes"
  echo "  ./scripts/publish-sync.sh --publish"
  echo ""
  echo "  # Pull Zach's changes AND publish"
  echo "  ./scripts/publish-sync.sh --sync-publish"
  exit 1
fi

# ==================================================================
# Shared: rename function (idempotent)
# ==================================================================
apply_renames() {
  echo "==> Applying @njdamstra scope renames..."

  # -- package.json names & repo URLs --
  for f in package.json packages/*/package.json; do
    [ -f "$f" ] || continue
    sed -i 's|https://github.com/zachhandley/AppwriteUtils|https://github.com/njdamstra/AppwriteUtils|g' "$f"
  done

  # Root monorepo name
  sed -i 's/"name": "appwrite-utils-monorepo"/"name": "@njdamstra\/appwrite-utils-monorepo"/' package.json

  # Individual package names (only if not already scoped)
  for pkg in appwrite-utils appwrite-utils-cli appwrite-utils-helpers appwrite-utils-mcp; do
    f="packages/$pkg/package.json"
    [ -f "$f" ] || continue
    sed -i "s/\"name\": \"$pkg\"/\"name\": \"@njdamstra\/$pkg\"/" "$f"
  done

  # Workspace dependency references
  for f in packages/*/package.json; do
    [ -f "$f" ] || continue
    sed -i 's/"appwrite-utils": "workspace:\*"/"@njdamstra\/appwrite-utils": "workspace:*"/g' "$f"
    sed -i 's/"appwrite-utils-helpers": "workspace:\*"/"@njdamstra\/appwrite-utils-helpers": "workspace:*"/g' "$f"
    sed -i 's/"appwrite-utils": "latest"/"@njdamstra\/appwrite-utils": "latest"/g' "$f"
    sed -i 's/"appwrite-utils-helpers": "latest"/"@njdamstra\/appwrite-utils-helpers": "latest"/g' "$f"
  done

  # -- Source imports (static + dynamic + multi-line) --
  for pkg in appwrite-utils-helpers appwrite-utils; do
    find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
      ! -path '*/node_modules/*' ! -name '*.backup' \
      -exec sed -i "s/from \"$pkg\"/from \"@njdamstra\/$pkg\"/g" {} +
    find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
      ! -path '*/node_modules/*' ! -name '*.backup' \
      -exec sed -i "s/from '$pkg'/from '@njdamstra\/$pkg'/g" {} +
    find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
      ! -path '*/node_modules/*' ! -name '*.backup' \
      -exec sed -i "s/import(\"$pkg\")/import(\"@njdamstra\/$pkg\")/g" {} +
    find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
      ! -path '*/node_modules/*' ! -name '*.backup' \
      -exec sed -i "s/import('$pkg')/import('@njdamstra\/$pkg')/g" {} +
    # Multi-line dynamic imports where string is on its own line
    find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
      ! -path '*/node_modules/*' ! -name '*.backup' \
      -exec sed -i "s/\"$pkg\"/\"@njdamstra\/$pkg\"/g" {} +
  done

  # -- Embedded string references --
  find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
    -exec sed -i 's/service: "appwrite-utils-cli"/service: "@njdamstra\/appwrite-utils-cli"/g' {} +
  find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
    -exec sed -i 's/generator: "appwrite-utils-cli"/generator: "@njdamstra\/appwrite-utils-cli"/g' {} +
  find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
    -exec sed -i 's/Generated by appwrite-utils-cli/Generated by @njdamstra\/appwrite-utils-cli/g' {} +
  find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
    -exec sed -i 's|github.com/zachhandley/appwrite-utils|github.com/njdamstra/AppwriteUtils|g' {} +
  find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
    -exec sed -i 's|github.com/zachhandley/AppwriteUtils|github.com/njdamstra/AppwriteUtils|g' {} +
  find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
    -exec sed -i 's/Appwrite Utils CLI Tool by Zach Handley/Appwrite Utils CLI Tool/g' {} +

  # -- README updates --
  for f in README.md packages/*/README.md packages/appwrite-utils-cli/src/config/README.md; do
    [ -f "$f" ] || continue
    sed -i 's/`appwrite-utils-cli`/`@njdamstra\/appwrite-utils-cli`/g' "$f"
    sed -i 's/npm install -g appwrite-utils-cli/npm install -g @njdamstra\/appwrite-utils-cli/g' "$f"
    sed -i 's/npm install appwrite-utils-cli/npm install @njdamstra\/appwrite-utils-cli/g' "$f"
    sed -i 's/--package=appwrite-utils-cli/--package=@njdamstra\/appwrite-utils-cli/g' "$f"
    sed -i 's/npx appwrite-utils-cli /npx @njdamstra\/appwrite-utils-cli /g' "$f"
    sed -i 's/`appwrite-utils`/`@njdamstra\/appwrite-utils`/g' "$f"
    sed -i 's/npm install appwrite-utils/npm install @njdamstra\/appwrite-utils/g' "$f"
    sed -i 's/from "appwrite-utils"/from "@njdamstra\/appwrite-utils"/g' "$f"
    sed -i "s/from 'appwrite-utils'/from '@njdamstra\/appwrite-utils'/g" "$f"
    sed -i 's/node_modules\/appwrite-utils/node_modules\/@njdamstra\/appwrite-utils/g' "$f"
  done

  # -- Check for stale references --
  STALE=$(grep -rn --include="*.ts" --include="*.js" \
    -E '(from|import\() ["'"'"']appwrite-utils(-helpers)?["'"'"']' packages/ \
    --exclude='*.backup' \
    --exclude-dir=node_modules || true)

  if [ -n "$STALE" ]; then
    echo "!! WARNING: Found un-renamed references:"
    echo "$STALE"
    echo "!! You may need to fix these manually."
  else
    echo "    All references renamed successfully."
  fi
}

# ==================================================================
# Shared: install & build
# ==================================================================
install_and_build() {
  echo "==> Installing dependencies..."
  pnpm install

  echo "==> Building all packages..."
  pnpm build

  echo "==> Build successful!"
}

# ==================================================================
# Shared: publish to npm
# ==================================================================
publish_packages() {
  echo "==> Publishing to npm..."

  # Read current versions
  UTILS_VER=$(node -p "require('./packages/appwrite-utils/package.json').version")
  HELPERS_VER=$(node -p "require('./packages/appwrite-utils-helpers/package.json').version")
  CLI_VER=$(node -p "require('./packages/appwrite-utils-cli/package.json').version")
  MCP_VER=$(node -p "require('./packages/appwrite-utils-mcp/package.json').version")

  echo "    Versions: utils=$UTILS_VER helpers=$HELPERS_VER cli=$CLI_VER mcp=$MCP_VER"

  # Temporarily swap workspace:* → real versions for publishing
  for f in packages/appwrite-utils-helpers/package.json packages/appwrite-utils-cli/package.json packages/appwrite-utils-mcp/package.json; do
    [ -f "$f" ] || continue
    sed -i "s/\"@njdamstra\/appwrite-utils\": \"workspace:\*\"/\"@njdamstra\/appwrite-utils\": \"^$UTILS_VER\"/" "$f"
    sed -i "s/\"@njdamstra\/appwrite-utils-helpers\": \"workspace:\*\"/\"@njdamstra\/appwrite-utils-helpers\": \"^$HELPERS_VER\"/" "$f"
  done

  # Publish in dependency order, skip if version already exists
  for pkg_dir in appwrite-utils appwrite-utils-helpers appwrite-utils-cli appwrite-utils-mcp; do
    dir="packages/$pkg_dir"
    [ -d "$dir" ] || continue
    PKG_NAME=$(node -p "require('./$dir/package.json').name")
    PKG_VER=$(node -p "require('./$dir/package.json').version")
    echo "    Publishing $PKG_NAME@$PKG_VER..."
    if cd "$dir" && npm publish --access public 2>&1 | tail -3; then
      echo "    OK: $PKG_NAME@$PKG_VER"
    else
      echo "    SKIP: $PKG_NAME@$PKG_VER (already published or error)"
    fi
    cd "$ROOT"
  done

  # Restore workspace:* refs
  for f in packages/appwrite-utils-helpers/package.json packages/appwrite-utils-cli/package.json packages/appwrite-utils-mcp/package.json; do
    [ -f "$f" ] || continue
    sed -i "s/\"@njdamstra\/appwrite-utils\": \"^$UTILS_VER\"/\"@njdamstra\/appwrite-utils\": \"workspace:*\"/" "$f"
    sed -i "s/\"@njdamstra\/appwrite-utils-helpers\": \"^$HELPERS_VER\"/\"@njdamstra\/appwrite-utils-helpers\": \"workspace:*\"/" "$f"
  done

  echo ""
  echo "==> Published:"
  echo "    @njdamstra/appwrite-utils@$UTILS_VER"
  echo "    @njdamstra/appwrite-utils-helpers@$HELPERS_VER"
  echo "    @njdamstra/appwrite-utils-cli@$CLI_VER"
  echo "    @njdamstra/appwrite-utils-mcp@$MCP_VER"
}

# ==================================================================
# Main execution
# ==================================================================

# ---- Sync upstream ----
if [ "$DO_SYNC" = true ]; then
  echo ""
  echo "========================================"
  echo "  SYNC UPSTREAM"
  echo "========================================"

  echo "==> Fetching upstream..."
  git fetch upstream dev

  echo "==> Merging upstream/dev..."
  if ! git merge upstream/dev --no-edit; then
    echo ""
    echo "!! Merge conflicts detected."
    echo "!! Resolve conflicts, then re-run this script to apply renames."
    echo "!! (The rename step is idempotent — safe to run multiple times.)"
    exit 1
  fi

  apply_renames
  install_and_build
fi

# ---- Publish ----
if [ "$DO_PUBLISH" = true ]; then
  echo ""
  echo "========================================"
  echo "  PUBLISH"
  echo "========================================"

  # If we didn't just sync, still need to build
  if [ "$DO_SYNC" = false ]; then
    install_and_build
  fi

  publish_packages
fi

# ---- Summary ----
echo ""
echo "========================================"
echo "  DONE"
echo "========================================"
if [ "$DO_SYNC" = true ]; then
  echo "  Next steps:"
  echo "    git add -A && git commit -m 'Sync upstream + re-apply @njdamstra scope'"
  echo "    git push origin dev"
fi
