#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------
# sync-upstream.sh
#
# Merge latest changes from ZachHandley/AppwriteUtils, re-apply
# @njdamstra scope renames, build, and optionally publish.
#
# Usage:
#   ./scripts/sync-upstream.sh              # merge + rename + build
#   ./scripts/sync-upstream.sh --publish    # also publish to npm
# ------------------------------------------------------------------

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PUBLISH=false
if [[ "${1:-}" == "--publish" ]]; then
  PUBLISH=true
fi

# ---- 1. Fetch & merge upstream ----
echo "==> Fetching upstream..."
git fetch upstream dev

echo "==> Merging upstream/dev..."
if ! git merge upstream/dev --no-edit; then
  echo ""
  echo "!! Merge conflicts detected."
  echo "!! Resolve conflicts, then re-run this script to apply renames."
  echo "!! (The rename step is idempotent — safe to run multiple times.)"
  exit 1
fi

# ---- 2. Re-apply @njdamstra scope renames ----
echo "==> Applying @njdamstra scope renames..."

# -- 2a. package.json names & repo URLs --
for f in package.json packages/*/package.json; do
  [ -f "$f" ] || continue
  # Repo URL
  sed -i 's|https://github.com/zachhandley/AppwriteUtils|https://github.com/njdamstra/AppwriteUtils|g' "$f"
done

# Root monorepo name
sed -i 's/"name": "appwrite-utils-monorepo"/"name": "@njdamstra\/appwrite-utils-monorepo"/' package.json

# Individual package names (only if not already scoped)
for pkg in appwrite-utils appwrite-utils-cli appwrite-utils-helpers appwrite-utils-mcp; do
  f="packages/$pkg/package.json"
  [ -f "$f" ] || continue
  sed -i "s/\"name\": \"$pkg\"/\"name\": \"@njdamstra\/$pkg\"/" "$f"
done

# Workspace dependency references in package.json files
for f in packages/*/package.json; do
  [ -f "$f" ] || continue
  sed -i 's/"appwrite-utils": "workspace:\*"/"@njdamstra\/appwrite-utils": "workspace:*"/g' "$f"
  sed -i 's/"appwrite-utils-helpers": "workspace:\*"/"@njdamstra\/appwrite-utils-helpers": "workspace:*"/g' "$f"
  sed -i 's/"appwrite-utils": "latest"/"@njdamstra\/appwrite-utils": "latest"/g' "$f"
  sed -i 's/"appwrite-utils-helpers": "latest"/"@njdamstra\/appwrite-utils-helpers": "latest"/g' "$f"
done

# -- 2b. Source imports (static: from "pkg" / from 'pkg') --
for pkg in appwrite-utils-helpers appwrite-utils; do
  find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
    ! -path '*/node_modules/*' ! -name '*.backup' \
    -exec sed -i "s/from \"$pkg\"/from \"@njdamstra\/$pkg\"/g" {} +
  find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
    ! -path '*/node_modules/*' ! -name '*.backup' \
    -exec sed -i "s/from '$pkg'/from '@njdamstra\/$pkg'/g" {} +
done

# -- 2c. Dynamic imports: import("pkg") / import('pkg') --
for pkg in appwrite-utils-helpers appwrite-utils; do
  find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
    ! -path '*/node_modules/*' ! -name '*.backup' \
    -exec sed -i "s/import(\"$pkg\")/import(\"@njdamstra\/$pkg\")/g" {} +
  find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
    ! -path '*/node_modules/*' ! -name '*.backup' \
    -exec sed -i "s/import('$pkg')/import('@njdamstra\/$pkg')/g" {} +
done

# -- 2d. Multi-line dynamic imports (import(\n  "pkg"\n)) --
for pkg in appwrite-utils-helpers appwrite-utils; do
  find packages/ -type f \( -name "*.ts" -o -name "*.js" \) \
    ! -path '*/node_modules/*' ! -name '*.backup' \
    -exec sed -i "s/\"$pkg\"/\"@njdamstra\/$pkg\"/g" {} +
done

# -- 2e. Embedded string references --
# Logging service name
find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
  -exec sed -i 's/service: "appwrite-utils-cli"/service: "@njdamstra\/appwrite-utils-cli"/g' {} +

# Constants generator name
find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
  -exec sed -i 's/generator: "appwrite-utils-cli"/generator: "@njdamstra\/appwrite-utils-cli"/g' {} +

# Config migration generated-by comment
find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
  -exec sed -i 's/Generated by appwrite-utils-cli/Generated by @njdamstra\/appwrite-utils-cli/g' {} +

# GitHub URLs in banners / info messages
find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
  -exec sed -i 's|github.com/zachhandley/appwrite-utils|github.com/njdamstra/AppwriteUtils|g' {} +
find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
  -exec sed -i 's|github.com/zachhandley/AppwriteUtils|github.com/njdamstra/AppwriteUtils|g' {} +

# Init banner author removal
find packages/ -type f -name "*.ts" ! -path '*/node_modules/*' \
  -exec sed -i 's/Appwrite Utils CLI Tool by Zach Handley/Appwrite Utils CLI Tool/g' {} +

# -- 2f. README updates --
for f in README.md packages/*/README.md packages/appwrite-utils-cli/src/config/README.md; do
  [ -f "$f" ] || continue
  # CLI package references (longer match first)
  sed -i 's/`appwrite-utils-cli`/`@njdamstra\/appwrite-utils-cli`/g' "$f"
  sed -i 's/npm install -g appwrite-utils-cli/npm install -g @njdamstra\/appwrite-utils-cli/g' "$f"
  sed -i 's/npm install appwrite-utils-cli/npm install @njdamstra\/appwrite-utils-cli/g' "$f"
  sed -i 's/--package=appwrite-utils-cli/--package=@njdamstra\/appwrite-utils-cli/g' "$f"
  sed -i 's/npx appwrite-utils-cli /npx @njdamstra\/appwrite-utils-cli /g' "$f"
  # Utils package references
  sed -i 's/`appwrite-utils`/`@njdamstra\/appwrite-utils`/g' "$f"
  sed -i 's/npm install appwrite-utils/npm install @njdamstra\/appwrite-utils/g' "$f"
  sed -i 's/from "appwrite-utils"/from "@njdamstra\/appwrite-utils"/g' "$f"
  sed -i "s/from 'appwrite-utils'/from '@njdamstra\/appwrite-utils'/g" "$f"
  sed -i 's/node_modules\/appwrite-utils/node_modules\/@njdamstra\/appwrite-utils/g' "$f"
done

# ---- 3. Verify no stale references ----
echo "==> Checking for stale references..."
STALE=$(grep -rn --include="*.ts" --include="*.js" \
  -E '(from|import\() ["'"'"']appwrite-utils(-helpers)?["'"'"']' packages/ \
  --exclude='*.backup' \
  --exclude-dir=node_modules || true)

if [ -n "$STALE" ]; then
  echo "!! WARNING: Found un-renamed references:"
  echo "$STALE"
  echo ""
  echo "!! You may need to fix these manually."
fi

# ---- 4. Install & build ----
echo "==> Installing dependencies..."
pnpm install

echo "==> Building all packages..."
pnpm build

echo ""
echo "==> Build successful!"

# ---- 5. Publish (optional) ----
if [ "$PUBLISH" = true ]; then
  echo "==> Publishing to npm..."

  # Read current versions
  UTILS_VER=$(node -p "require('./packages/appwrite-utils/package.json').version")
  HELPERS_VER=$(node -p "require('./packages/appwrite-utils-helpers/package.json').version")
  CLI_VER=$(node -p "require('./packages/appwrite-utils-cli/package.json').version")
  MCP_VER=$(node -p "require('./packages/appwrite-utils-mcp/package.json').version")

  # Temporarily swap workspace:* → real versions for publishing
  for f in packages/appwrite-utils-helpers/package.json packages/appwrite-utils-cli/package.json packages/appwrite-utils-mcp/package.json; do
    sed -i "s/\"@njdamstra\/appwrite-utils\": \"workspace:\*\"/\"@njdamstra\/appwrite-utils\": \"^$UTILS_VER\"/" "$f"
    sed -i "s/\"@njdamstra\/appwrite-utils-helpers\": \"workspace:\*\"/\"@njdamstra\/appwrite-utils-helpers\": \"^$HELPERS_VER\"/" "$f"
  done

  # Publish in dependency order
  cd packages/appwrite-utils && npm publish --access public && cd "$ROOT"
  cd packages/appwrite-utils-helpers && npm publish --access public && cd "$ROOT"
  cd packages/appwrite-utils-cli && npm publish --access public && cd "$ROOT"
  cd packages/appwrite-utils-mcp && npm publish --access public && cd "$ROOT"

  # Restore workspace:* refs
  for f in packages/appwrite-utils-helpers/package.json packages/appwrite-utils-cli/package.json packages/appwrite-utils-mcp/package.json; do
    sed -i "s/\"@njdamstra\/appwrite-utils\": \"^$UTILS_VER\"/\"@njdamstra\/appwrite-utils\": \"workspace:*\"/" "$f"
    sed -i "s/\"@njdamstra\/appwrite-utils-helpers\": \"^$HELPERS_VER\"/\"@njdamstra\/appwrite-utils-helpers\": \"workspace:*\"/" "$f"
  done

  echo ""
  echo "==> Published:"
  echo "    @njdamstra/appwrite-utils@$UTILS_VER"
  echo "    @njdamstra/appwrite-utils-helpers@$HELPERS_VER"
  echo "    @njdamstra/appwrite-utils-cli@$CLI_VER"
  echo "    @njdamstra/appwrite-utils-mcp@$MCP_VER"
fi

# ---- 6. Summary ----
echo ""
echo "==> Done! Next steps:"
echo "    1. Review changes: git diff"
echo "    2. Commit: git add -A && git commit -m 'Sync upstream + re-apply @njdamstra scope'"
echo "    3. Push: git push origin dev"
if [ "$PUBLISH" = false ]; then
  echo "    4. Publish: ./scripts/sync-upstream.sh --publish"
fi
